language: java
sudo: required
dist: trusty
jdk: oraclejdk8

before_install:
  - wget https://archive.apache.org/dist/maven/maven-3/3.2.2/binaries/apache-maven-3.2.2-bin.tar.gz
  - tar xf apache-maven-3.2.2-bin.tar.gz
  - export M2_HOME=$PWD/apache-maven-3.2.2
  - export PATH=$M2_HOME/bin:$PATH

addons:
  apt:
    packages:
      - oracle-java8-installer
   
cache:
  directories:
  - $HOME/.m2/repository
  
before_cache:
  - rm -f $HOME/.m2/repository/com/torodb

before_script:
  - export GIT_BRANCH=$TRAVIS_BRANCH

script: mvn -Psafer -Pintegration -B -e -T 1C -Dcheckstyle.consoleOutput=false verify

after_success:
  - |
    if [ "$TRAVIS_EVENT_TYPE" != cron ] && [ "$TRAVIS_REPO_SLUG" == gortiz/server ]
    then
        bash <(curl -s https://codecov.io/bash) || echo 'Codecov did not collect coverage reports'
    else
        echo 'Codecov not notified'
    fi
  